image: atlassian/default-image:2
pipelines:
  branches:
    devops:
      - step:
          name: Build and AWS Setup
          services:
            - docker
          script:
            - VERSION="${BITBUCKET_BUILD_NUMBER}"
            # builds docker image from a local dockerfile
            - docker build -t ${DOCKER_IMAGE_NAME} .
            # use pipe to push the image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.3.0
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                IMAGE_NAME: ${DOCKER_IMAGE_NAME}
                TAGS: ${BITBUCKET_COMMIT}
      - step:
          name: "Deploy to PROD"
          script:
          - envsubst < deployment.tpl.yaml > deployment.yaml
          - cat deployment.yaml
          - pipe: atlassian/aws-eks-kubectl-run:2.2.0
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              CLUSTER_NAME: "tekrevol-stage"
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment.yaml"
              DEBUG: "true"
