apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  name: serveeasy
  labels:
    app: serveeasy
    env: stage
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveeasy
  template:
    metadata:
      labels:
        app: serveeasy
    spec:
      containers:
        - name: serveeasy
          image: 307866862898.dkr.ecr.us-east-1.amazonaws.com/serveeasy
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: serveeasy
  namespace: stage
spec:
  type: NodePort
  selector:
    app: serveeasy
  ports:
  - port: 4010
    name: http